### ISSUE TITLE
 The remote host closed the connection. 

### ISSUE THREAD

**Issue by totpero** [IdentityServer/IdentityServer3#2232] opened 2015-11-29 15:22 UTC
Hello, i have idsrv3 with last update and in log i have regularly this error:

```2015-11-29 05:50:23.098 +02:00 [Error] Unhandled exception
System.Web.HttpException (0x800704CD): The remote host closed the connection. The error code is 0x800704CD.
   at System.Web.Hosting.IIS7WorkerRequest.RaiseCommunicationError(Int32 result, Boolean throwOnDisconnect)
   at System.Web.Hosting.IIS7WorkerRequest.ExplicitFlush()
   at System.Web.HttpResponse.Flush(Boolean finalFlush, Boolean async)
   at System.Web.HttpWriter.WriteFromStream(Byte[] data, Int32 offset, Int32 size)
   at System.IO.Stream.<BeginWriteInternal>b__11(Object param0)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.IO.Stream.EndWrite(IAsyncResult asyncResult)
   at Microsoft.Owin.Host.SystemWeb.CallStreams.OutputStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.Http.StreamToStreamCopy.BufferWrittenCallback(IAsyncResult ar)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Owin.HttpMessageHandlerAdapter.<SendResponseContentAsync>d__20.MoveNext()```

**Comment by brockallen** [comment] 2015-11-29 17:12
What path/URL?

**Comment by jageall** [comment] 2015-11-29 17:48
it is probably a firewall or load balancer disconnecting the request if you
get it a lot, there isn't really a lot that can be done about it as it can
also be caused by people navigating away or closing their browser etc

see #1142, #1968

**Comment by totpero** [comment] 2015-11-29 19:29
in the same message log group, before this error i get this info message:
```2015-11-29 10:53:23.582 +02:00 [Information] Login page requested
2015-11-29 10:53:23.582 +02:00 [Information] rendering login page```

**Comment by HaggeMan** [comment] 2015-11-30 07:05
Don't know if you use Kentor.CookieSaver to sort redirect infinite loop; but we experience the behavior you're describing when using Kentor. After removal av Kentor the page responded correctly again but we still have issues with infinity loops for some users.

**Comment by totpero** [comment] 2015-11-30 12:33
i don't use Kentor.CookieSaver

**Comment by leastprivilege** [comment] 2015-12-19 16:44
any progress? closing. feel free to re-open if needed.

**Closed by leastprivilege** 2015-12-19 16:44 UTC
Labels: question
