### ISSUE TITLE
Dead On Arrival Request In Windows Azure

### ISSUE THREAD

**Issue by khalidabuhakmeh** [IdentityServer/IdentityServer3#2202] opened 2015-11-23 19:27 UTC
We have been using IdentityServer v3 for a year now inside of Windows Azure. Everything works as expected 99% of the time, but every once in a while we get a strange occurrence where none of our users can log into our applications.

Our environment mixes membership reboot and Azure AD for authentication. We also utilize the `Microsoft.Owin.Security.OpenIdConnect` middleware for processing the `jwt`.

Below is the behavior we are seeing:

1. The user attempts to log into our client application.
2. User logs in via IdentityServer host
3. The user is redirected back the client application with the token.
4. Token begins to be processed.

Expected behavior:

- User is logged into the application

Actual behavior: 

- User's request abruptly stops when authentication-request flows form host to client via `POST`. Instead of receiving a `301` to the client's `redirectUri`, a `200` is received with no `Location` nor `Set-Cookie` headers.

**note: we can only get this behavior in Azure, and cannot reproduce locally.**

Current resolution:

- We can resolve this problem by restarting the app. in Azure.

Behavior notes:

- Users who already have a client cookie do not experience this issue. This issue only happens with unauthenticated requests.

___

- Do you guys have any idea where we can start to debug this issue?
- Do you have any time available for consulting to solve this issue?

Thanks,

@khalidabuhakmeh and @billboga

**Comment by brockallen** [comment] 2015-11-23 19:52
A point of clarification (with the assumption that the client app is a server side app, like MVC): to issue the token from IdSvr to the client, IdSvr renders a `<form>` (with the token) and JS in the rendered page submits the form to the client. So there is no redirect from IdSvr back to the client; it should be a 200, but immediately POST to the client. 

If the client app is JS/SPA-based, then it would be a redirect.

I don't recall which of these two types your client apps are.

**Comment by khalidabuhakmeh** [comment] 2015-11-23 19:54
It is the `<form>` post from the JS in the rendered page that submits the form to the client.

**Comment by brockallen** [comment] 2015-11-23 19:57
Ok, so then there should not be any redirects or Location headers set in the final stage of the exchange. Also, the only time a cookie should be issued is from the login page (not the authorization endpoint).

So having said that, from your description I'm not sure I follow where things break down. It sounds like something happens where the token is just not submitted back to the client...

**Comment by billboga** [comment] 2015-11-23 20:37
@brockallen: here is a sample screen shot of the request in the auth pipeline prior to the request ending:

![image](https://cloud.githubusercontent.com/assets/3382469/11348920/521f6176-91f7-11e5-8009-c665d55d8ed2.png)

There is no content returned by the request. We have discovered if we `throw` inside the following code, we _can_ duplicate a similar behavior. We are not sure, however, if that is related to our current Azure problem.

```csharp
app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                //... boilerplate
                Notifications = new OpenIdConnectAuthenticationNotifications
                {                    
                    SecurityTokenValidated = n =>
                    {
                        throw new ApplicationException("you got me");
                    }
                }
            }
```

When throwing, we have found a need for the following to keep the request pipeline moving:

```csharp
app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                Notifications = new OpenIdConnectAuthenticationNotifications
                {                
                    AuthenticationFailed = n =>
                    {
                        n.State = Microsoft.Owin.Security.Notifications.NotificationResultState.Skipped;

                        return Task.FromResult(true);
                    }
                }
            }
```

**Comment by brockallen** [comment] 2015-11-23 21:03
It looks like you're getting the form back from IdSvr with the contents needed (id_token, etc). I can't tell if the JS is doing the submit. If the user has JS disabled, then they'd not even get this far, so I'll assume the JS is submitting the form. 

So then my sense is that the problem is coming from the client application, and somewhere in the Katana OIDC middleware. If the POST is not getting back a response then it might be due to the katana deadlock issue? Does the request time out in the browser? Or is it that the server responds with an 200 and an empty response body?

**Comment by billboga** [comment] 2015-11-23 21:06
JS is submitting the form. It's just the client app. responding with a 200 and empty response body.

**Comment by brockallen** [comment] 2015-11-23 21:08
Might this happen as the client app experiences an apppool recycle? I'm wondering if the call to lookup metadata is failing (for some reason) and then it just halts. I'd expect an exception, though, to be honest.

**Comment by brockallen** [comment] 2015-11-23 21:11
Also, perhaps look into enabling katana logging in the client app -- maybe the OIDC MW will tell you what's happening.

**Comment by khalidabuhakmeh** [comment] 2015-11-24 19:02
We found that the current OIDC MW is flawed in the way it logs exceptions. I believe we are narrowing it down to an exception happening in the MW that may have to do with the `Notifications` object. An exception in the MW is killing the entire chain of OWIN MW and leaving us at a white screen. 

We are currently working on putting a better logging mechanism around OWIN and our clients to see what the error is in these instances. We will keep reporting back for others.

**Comment by brockallen** [comment] 2015-11-24 19:07
Were you able to identify the problem that triggers the problem?

**Comment by khalidabuhakmeh** [comment] 2015-11-24 19:13
Not yet, we are hoping to deploy something into production soon and then it is a wait and hope it happens again in the next week.

**Comment by brockallen** [comment] 2015-11-24 19:24
Also, for the users that had the problem, were they able to "start over" and eventually get logged in? Just trying to figure out if it's a browser/user issue, or a server issue.

**Comment by billboga** [comment] 2015-12-01 15:19
Our current resolution is to restart the client app. in Azure (we never have to restart the host app). We have recently deployed better OWIN error logging to one of our app.'s QA environments and will report back if/when the problem occurs again.

**Comment by brockallen** [comment] 2015-12-01 17:06
Ok, thanks. I'l[l close this for now, but feel free to post follow up here (or re-open if necessary).

**Closed by brockallen** 2015-12-01 17:06 UTC
Labels: question
