### ISSUE TITLE
ASP.NET Core 1.0 Bug (Kestrel)

### ISSUE THREAD

**Issue by rh78** [IdentityServer/IdentityServer3#3059] opened 2016-07-13 14:31 UTC
Hi guys, I found a bug in ASP.NET Core 1.0 with IdentityServer 3. I know you're focusing on the version 4, but as many users still will be on version 3 until 4 is stable, they'll need this fix to use it.

Actually the problem is in ValidateAntiForgeryTokenAttribute.cs. There you're overwriting the request stream, which causes significant trouble in Kestrel. Actually once you did this, every further request will not contain the new body content, but the old one, breaking the whole system. It seems to be an issue with HttpContexts being reused, but out of sync because of the "dirty" change.

I fixed it by setting the request body stream copy before IsTokenValid, and setting it back to the original stream afterwards. Then it works. Here's my code:

---
                var bytes = await actionContext.Request.Content.ReadAsByteArrayAsync();
                var ms = new MemoryStream(bytes);
                ms.Seek(0, SeekOrigin.Begin);
                var ctx = new OwinContext(env);

                Stream oldStream = ctx.Request.Body;

                ctx.Request.Body = ms;

                var antiForgeryToken = env.ResolveDependency<AntiForgeryToken>();
                success = await antiForgeryToken.IsTokenValid();

                ms.Dispose();

                ctx.Request.Body = oldStream;
---

**Comment by brockallen** [comment] 2016-07-13 15:21
Do all the tests pass with this change? Does this work in katana as well?

If you submit a PR with the change then our CI can test these things. Thx

**Comment by rh78** [comment] 2016-07-13 17:03
Hi i have a fork with some other changes so I cannot guarantee all tests pass with this change alone also I did not test on Katana. Just wanted to get this hint to you guys (I think for PR I need GitHub fork which I don't have its local on our dev server).

**Comment by rh78** [comment] 2016-07-13 17:06
PS but chances are good that the change results in less side effects than the old solution because rest of framework will continue with original stream. Just changing underlying without reverting is kind of "mega dirty".

PS: what happened to XSRF protection in IdentityServer4? Will it be responsibility of client side code?

**Comment by leastprivilege** [comment] 2016-07-13 17:07
So fork the repo, make that change and send a pr. From there it is in CI.

**Comment by rh78** [comment] 2016-07-13 17:09
Ok will do ASAP.

**Comment by rh78** [comment] 2016-07-13 17:23
Done

**Comment by Marfusios** [comment] 2016-07-14 07:10
Looks very similar to my issue. 
Is it somehow related to https://github.com/IdentityServer/IdentityServer3/issues/3057 ?

**Comment by rh78** [comment] 2016-07-14 07:29
Yeah thats definitely it, should be fixed with this.

**Comment by Marfusios** [comment] 2016-07-14 10:07
It didn't help me, but it is definitely the right way, so thanks for figuring it out.

I've fixed it and created pull request (https://github.com/IdentityServer/IdentityServer3/pull/3069), all tests are passing but somebody should review it.

**Comment by brockallen** [comment] 2016-07-19 14:09
Thanks -- I'll get to it when I can.

**Comment by travisjweber** [comment] 2016-08-09 16:37
Building on the middleware approach... I was able to get this working with zero changes to the IDS packages by adding it as a plugin when configuring Identity Server.

Using ASP.NET Core, targeting .NET 4.6.2 hosted in IIS (the problem did not arise when running via dotnet run locally).

```
    public class Ids3Issue3059TemporaryWorkaround
    {
         private readonly Func<IDictionary<string, object>, Task> _next;
 
         public Ids3Issue3059TemporaryWorkaround(Func<IDictionary<string, object>, Task> next)
         {
             _next = next;
         }
 
         public async Task Invoke(IDictionary<string, object> env)
         {
             var context = new OwinContext(env);
 
             var oldStream = context.Request.Body;
             var body = new StreamReader(context.Request.Body).ReadToEnd();
             var requestData = Encoding.UTF8.GetBytes(body);
             context.Request.Body = new MemoryStream(requestData);
 
            await _next(env);
 
             context.Request.Body = oldStream;
         }
    }

and then add it to your IDS options

    var idsrvOptions = new IdentityServerOptions
    {
        //other options omitted here...
       PluginConfiguration = (builder, options) =>
        {
        builder.Use<Ids3Issue3059TemporaryWorkaround>();
        }
    };
            
app.UseIdentityServer(idsrvOptions);

```

**Comment by rh78** [comment] 2016-08-09 16:42
Cool idea, really!

**Comment by brockallen** [comment] 2016-08-10 20:31
So I now have 3 different PRs all trying to solve the same problem. Here's the simplest one, I think: https://github.com/IdentityServer/IdentityServer3.Integration.AspNetCore/pull/11/commits/d7e113549f4fe6c62e6baad4a97d61d234c8623c. If we accept any of them, I think I like this approach the best -- it leaves the current code inside of IdSvr alone and solve it via the upstream middleware.

Now, this PR is putting the middleware in the ASP.NET Core integration layer. So I think the real question is: do we want this done in the ASP.NET integration package, or should this just be internalized inside of IdSvr core itself?

**Comment by timscriv** [comment] 2016-08-10 23:40
It seemed to me that it was a problem with AspNet Cote working with OWIN properly so the middleware seemed the best location since the problem is not IdSvr.

**Comment by brockallen** [comment] 2016-08-11 00:06
Well, it also works in Katana. So I was wondering if it made sense to just put it into IdSvr core so that if someone was not using the integration library that it'd still work.

**Comment by rh78** [comment] 2016-08-11 06:01
IMHO modifying an underlying stream (without ownership) and not reverting it back to the original after being done is not as it should be, in any way. Its just not clean coding, even if it works. So I suggest fixing it in IdSvr because of that reason.

**Comment by rh78** [comment] 2016-08-11 06:03
Ps i think marfusios invested more work to fix all possible occurences of the bug while I fixed only the one related to my use case so maybe his PR is better.

**Comment by Marfusios** [comment] 2016-08-11 07:50
@rh78 I just extended your PR, found all other occurrences in a code and applied the fix. So both PRs must be merged. 

But perhaps we should merge just PR from IdentityServer3.Integration.AspNetCore, it seems cleaner, because it won't affect every IdentityServer use-cases, just when used with .NET Core.

**Comment by brockallen** [comment] 2016-08-11 15:01
> MHO modifying an underlying stream (without ownership) and not reverting it back to the original after being done is not as it should be, in any way.

Sorry, I'm confused -- which PR/approach do you mean in your comment? Thx.

**Comment by rh78** [comment] 2016-08-11 15:12
Hi i mean none of the PRs. I mean the as-is situation. It just should not be like it is. So it should be fixed in IdSrv and not by using the middleware approach.

**Comment by brockallen** [comment] 2016-08-11 15:23
@rh78 ah ok, thanks for clarifying.

**Comment by brockallen** [comment] 2016-08-11 15:25
@rh78 BTW, did you try the middleware approach? if so, did it fix your problem?

**Comment by rh78** [comment] 2016-08-11 15:33
No didn't try it as I fixed it and made own build of idsrv temporarily until fixed Version is released

**Comment by brockallen** [comment] 2016-08-11 15:40
I was hoping you'd try the middleware approach to confirm if it works for you :)

**Comment by rh78** [comment] 2016-08-11 16:00
Sure it will work See no reason why it shouldn't.

**Comment by brockallen** [comment] 2016-08-11 16:24
I'm looking more at the PRs, and I'm leaning towards the middleware approach. Also, it seems like a bug in ASP.NET Core's OWIN integration layer... perhaps we should let them know.

**Comment by rh78** [comment] 2016-08-11 17:06
As I said IMHO if you change something that you do not own you shouldn't leave it changed but fix it afterwards.

**Comment by brockallen** [comment] 2016-08-11 18:00
Here's my proposal for fixes based upon this and other PRs: https://github.com/IdentityServer/IdentityServer3/pull/3132

**Comment by rh78** [comment] 2016-08-11 20:01
Looks good it is a good mix IMHO. However at the back of m head I think marfusios found the "copy" code at more than one place. Did you remove all occurences?

**Comment by brockallen** [comment] 2016-08-11 20:18
The only place I really wanted to cleanup was the hacky code I had to do for the antixsrf based on how WebAPI internally did the buffering; I removed it in this PR. As for the others, they check to see if the request stream is seekable, which now it should always be. Perhaps I could remove those as well...

**Comment by rh78** [comment] 2016-08-12 06:40
Your decision :-) thanks for fixing!

**Comment by flytzen** [comment] 2016-08-12 16:11
I don't know if it's helpful, but running locally, this works if you switch over to WebListener instead of Kestrel.  I only mention in it as it does support the case that there is something odd going on in the Kestrel code.
Of course, using WebListener doesn't really help when you want to host in production.3

Thanks to all of you for doing so much work on this; you've just saved me :)

**Comment by brockallen** [comment] 2016-08-12 16:57
Ok, I merged it. Thanks for everyone researching this and essentially solving the problem with your efforts and PRs. Thanks!

**Closed by brockallen** 2016-08-12 16:57 UTC
Labels: bug fix
