### ISSUE TITLE
Error while accessing the WsFederation endpoint

### ISSUE THREAD

**Issue by rite2sanjay** [IdentityServer/IdentityServer3#2409] opened 2016-01-13 18:08 UTC
I am configuring the WsFed plugin and am getting an error when I access the metadata endpoint /wsfed/metadata.

Here is the error I am encountering from identity server
ID3203: An error occurred while writing the metadata document. Required parameter 'entityID' is not set.

Am I missing any setting? Thanks for your help.

WsFed plugin options
var factory = new WsFederationServiceFactory(options.Factory);
factory.Register(new Registration<IEnumerable<RelyingParty>>(RelyingParties.Get()));
factory.RelyingPartyService = new Registration<IRelyingPartyService>(typeof(InMemoryRelyingPartyService));

var wsFedOptions = new WsFederationPluginOptions
            {
                EnableMetadataEndpoint = true,
                IdentityServerOptions = options,
                Factory = factory
            };

Relying party configuration
new RelyingParty
                {                    
                    Name = "ADFS",
                    Enabled = true,
                    Realm = "urn:adfs",
                    IncludeAllClaimsForUser = true,
                    ReplyUrl = "https://adfsurl/adfs/ls",
                    TokenLifeTime = 1,
                    ClaimMappings = new Dictionary<string, string>
                    {
                        { "sub", ClaimTypes.NameIdentifier },
                        { "name", ClaimTypes.Name },
                        { "given_name", ClaimTypes.GivenName },
                        { "email", ClaimTypes.Email }
                    }                    
                }

StackTrace:
at System.IdentityModel.Metadata.MetadataSerializer.WriteEntityDescriptor(XmlWriter inputWriter, EntityDescriptor entityDescriptor)\r\n at System.IdentityModel.Metadata.MetadataSerializer.WriteMetadataCore(XmlWriter writer, MetadataBase metadataBase)\r\n at System.IdentityModel.Metadata.MetadataSerializer.WriteMetadata(XmlWriter writer, MetadataBase metadata)\r\n at IdentityServer3.WsFederation.Results.MetadataResult.Execute() in c:\\local\\identity\\server3\\WsFederation\\source\\WsFederationPlugin\\Results\\MetadataResult.cs:line 53\r\n at IdentityServer3.WsFederation.Results.MetadataResult.ExecuteAsync(CancellationToken cancellationToken) in c:\\local\\identity\\server3\\WsFederation\\source\\WsFederationPlugin\\Results\\MetadataResult.cs:line 45\r\n at System.Web.Http.Controllers.ApiControllerActionInvoker.d__0.MoveNext() in c:\\local\\identity\\model\\IdentityModel\\source\\IdentityModel.Net45\\Identity.cs:line 0\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n at System.Web.Http.Filters.ActionFilterAttribute.d__5.MoveNext() in c:\\local\\identity\\model\\IdentityModel\\source\\IdentityModel.Net45\\Identity.cs:line 0\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n at System.Web.Http.Filters.ActionFilterAttribute.d__5.MoveNext() in c:\\local\\identity\\model\\IdentityModel\\source\\IdentityModel.Net45\\Identity.cs:line 0\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n at System.Web.Http.Filters.ActionFilterAttribute.d__0.MoveNext() in c:\\local\\identity\\model\\IdentityModel\\source\\IdentityModel.Net45\\Identity.cs:line 0\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n at System.Web.Http.Filters.ActionFilterAttribute.d__5.MoveNext() in c:\\local\\identity\\model\\IdentityModel\\source\\IdentityModel.Net45\\Identity.cs:line 0\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n at System.Web.Http.Filters.ActionFilterAttribute.d__5.MoveNext() in c:\\local\\identity\\model\\IdentityModel\\source\\IdentityModel.Net45\\Identity.cs:line 0\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n at System.Web.Http.Filters.ActionFilterAttribute.d__0.MoveNext() in c:\\local\\identity\\model\\IdentityModel\\source\\IdentityModel.Net45\\Identity.cs:line 0\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n at System.Web.Http.Controllers.ActionFilterResult.d__2.MoveNext() in c:\\local\\identity\\model\\IdentityModel\\source\\IdentityModel.Net45\\Identity.cs:line 0\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n at System.Web.Http.Controllers.AuthenticationFilterResult.d__0.MoveNext() in c:\\local\\identity\\model\\IdentityModel\\source\\IdentityModel.Net45\\Identity.cs:line 0\r\n--- End of stack trace from previous location where exception was thrown ---\r\n at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n at System.Web.Http.Dispatcher.HttpControllerDispatcher.d__1.MoveNext() in c:\\local\\identity\\model\\IdentityModel\\source\\IdentityModel.Net45\\Identity.cs:line 0

**Comment by brockallen** [comment] 2016-01-14 12:48
Do you have the smallest sample to reproduce this that you can share with us?

**Comment by rite2sanjay** [comment] 2016-01-14 19:38
[IdentityWsFedPlugin.zip](https://github.com/IdentityServer/IdentityServer3/files/90902/IdentityWsFedPlugin.zip)

Hi Brock, Attached is the sample. Thanks.

**Comment by brockallen** [comment] 2016-01-17 11:56
Ok, I was able to repro this -- it's due to some internal changes we made to the Issuer logic in IdSvr and these changes didn't get reflected in the WS-Fed plugin. 

As a workaround for now, you can explicitly set the IssuerUri in the IdSvr config.

**Comment by brockallen** [comment] 2016-01-17 12:46
Closing this to track here: https://github.com/IdentityServer/IdentityServer3.WsFederation/issues/57

**Closed by brockallen** 2016-01-17 12:46 UTC
Labels: bug

**Comment by brockallen** [comment] 2016-01-17 12:57
Fixed in this release: https://github.com/IdentityServer/IdentityServer3.WsFederation/releases/tag/2.0.5

Please test it and let us know how it works.

**Comment by rite2sanjay** [comment] 2016-01-18 17:35
Setting the IssuerUri resolved the issue. Thanks Brock for the quick response.

**Comment by brockallen** [comment] 2016-01-18 17:36
I released a patch for this yesterday -- please try it and see if it works for you. With the patch, you shouldn't need to set the IssuerUri.

**Comment by rite2sanjay** [comment] 2016-01-19 00:14
Awesome. The patch works as well. Thanks.
