### ISSUE TITLE
Question about CORS

### ISSUE THREAD

**Issue by imperugo** [IdentityServer/IdentityServer3#1293] opened 2015-05-01 08:40 UTC
Hi,
I'm using Identity Server on my project but I've having some issues with CORS.
During login procedure I've this warning:

CORS request made for path: /login from origin: https://auth.mywebsite.it but rejected because invalid CORS path.

Into my Identity Server configuration I've enabled CORS:

```csharp
identityServerOptions.CorsPolicy.AllowedOrigins.Add("https://auth.mywebsite.it");
identityServerOptions.CorsPolicy.AllowedOrigins.Add("https://api.mywebsite.it");
identityServerOptions.CorsPolicy.AllowedOrigins.Add("https://www.mywebsite.it");
```

As you can see here for the response headers for "/login" request the "Access-Control-Allow-Origin" is missing.

![2015-05-01_10-38-47](https://cloud.githubusercontent.com/assets/758620/7428289/60386920-efee-11e4-81e0-e5ddc82b2373.jpg)

Finally the request contains the CORS header ("Origin") but the domain of the call and the idsrv domain are the same, so is not a CORS call.

Where am I wrong?

**Comment by brockallen** [comment] 2015-05-03 16:56
Do you have a CORS service also registered? If you have both, then the explicit CORS service overrides the v1 approach.

**Comment by imperugo** [comment] 2015-05-03 17:12
Nope, only idsrv in that installation

**Comment by brockallen** [comment] 2015-05-03 17:55
And what are the logs saying about CORS? Also, what exact version are you using?

**Comment by imperugo** [comment] 2015-05-03 17:58
here the installed version

```xml
<package id="Thinktecture.IdentityModel.Core" version="1.4.0" targetFramework="net45" />
<package id="Thinktecture.IdentityServer3" version="1.4.1" targetFramework="net45" />
<package id="Thinktecture.IdentityServer3.AccessTokenValidation" version="1.2.2" targetFramework="net45" />
<package id="Thinktecture.IdentityServer3.EntityFramework" version="1.2.0" targetFramework="net45" />
```

about the log just this message

2015-05-01 21:32:12.984 +00:00 [Warning] CORS request made for path: /login from origin: https://auth.mydomain.it but rejected because invalid CORS path

**Comment by brockallen** [comment] 2015-05-08 21:02
Did we make any progress on this issue? Sorry if I lost track.

**Comment by imperugo** [comment] 2015-05-10 06:40
Nope, still here.

**Comment by jawadatgithub** [comment] 2015-05-10 06:54
I have the same issue as well, even with 1.6 update:

> 2015-05-09 00:26:08.8430|INFO|rendering login page
2015-05-09 00:26:09.8721|WARN|CORS request made for path: /login from origin: https://login.---.com but rejected because invalid CORS path

I am not using `CorsPolicy` because its deprecated as per docs. I am using CORS as below after defining `AllowedCorsOrigins` under client config:

```
var cors = new InMemoryCorsPolicyService(Clients.Get());
factory.CorsPolicyService = new Registration<Thinktecture.IdentityServer.Core.Services.ICorsPolicyService>(cors);
```

**Comment by imperugo** [comment] 2015-05-14 10:03
@jawadatgithub confirmed.
Also using ICorsPolicyService the problem still here (v 1.6.1 tested with sample repository)

**Comment by brockallen** [comment] 2015-05-14 11:43
Yep, sorry -- been traveling so haven't had time to try to repo this, but this issue is the next one on my list.

**Comment by brockallen** [comment] 2015-05-14 13:39
@jawadatgithub if you set the `CorsPolicyService` then the `CorsPolicy` settings are not used.

**Comment by brockallen** [comment] 2015-05-14 13:42
@imperugo i just tried to reproduce this with the "JavaScript Implicit Client - TokenManager". I removed the `CorsPolicy.AllowAll` and tried to run the client and got these errors in the log:

```
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Configuration.Hosting.CorsPolicyProvider]: 5/14/2015 1:37:16 PM +00:00 -- CORS request made for path: /.well-known/openid-configuration from origin: http://localhost:21575
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Services.Default.DefaultCorsPolicyService]: 5/14/2015 1:37:16 PM +00:00 -- AllowedOrigins configured and origin http://localhost:21575 is not allowed
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Services.Default.DefaultCorsPolicyService]: 5/14/2015 1:37:16 PM +00:00 -- Exiting; origin http://localhost:21575 is not allowed
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Configuration.Hosting.CorsPolicyProvider]: 5/14/2015 1:37:16 PM +00:00 -- CorsPolicyService did not allow origin
```

Once I then added the origin:
```
idsrvOptions.CorsPolicy.AllowedOrigins.Add("http://localhost:21575");
```

It was then successful:

```
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Configuration.Hosting.CorsPolicyProvider]: 5/14/2015 1:38:32 PM +00:00 -- CORS request made for path: /.well-known/openid-configuration from origin: http://localhost:21575
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Services.Default.DefaultCorsPolicyService]: 5/14/2015 1:38:32 PM +00:00 -- AllowedOrigins configured and origin http://localhost:21575 is allowed
iisexpress.exe Information: 0 : [Thinktecture.IdentityServer.Core.Configuration.Hosting.CorsPolicyProvider]: 5/14/2015 1:38:32 PM +00:00 -- CorsPolicyService allowed origin
```

So I can't reproduce the error. Can you test against the sample clients to confirm the same results?

**Comment by PoyaManouchehri** [comment] 2015-05-15 09:48
I can also repro the issue. It happens for me when an external IdP posts back a token (WS-Fed) to a custom url defined by CallbackPath. Note that the external IdP and identity server must be on different domains to get a repro.

Also looking at the code, this check is in CorsPolicyProvider.IsPathAllowed(), i.e. before actually getting to execute the ICorsPolicyService method. It looks like there is a fixed set of allowed paths and I don't see a way to change it.

**Comment by brockallen** [comment] 2015-05-17 16:19
Can you provide me with the smallest sample that reproduces it?

**Comment by jawadatgithub** [comment] 2015-05-17 17:41
I just downloaded fresh selfhost (minimal), update nuget packages, run without changing any bits of code or config, then browse to https://localhost:44333/core , click [application permissions](https://localhost:44333/core/permissions), login with bob:bob , open trace.log:

> SelfHost.vshost.exe Information: 0 : [Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController]: 17/5/2015 5:35:51 PM +00:00 -- rendering login page
SelfHost.vshost.exe **Warning**: 0 : [Thinktecture.IdentityServer.Core.Configuration.Hosting.CorsPolicyProvider]: 17/5/2015 5:35:55 PM +00:00 -- CORS request made for path: /login from origin: https://localhost:44333 **but rejected because invalid CORS path**
SelfHost.vshost.exe Information: 0 : [Thinktecture.IdentityServer.Core.Endpoints.AuthenticationController]: 17/5/2015 5:35:55 PM +00:00 -- Login page submitted

**Comment by PoyaManouchehri** [comment] 2015-05-18 01:59
Just wanted to give a quick update on my situation which is slightly different but might help others:

1) The "rejected because invalid CORS path" warning was red herring in my situation and was inconsequential. I was getting it when an external provider posted an authentication token back to Identity Server on a custom `CallbackPath`. In this situation you will get the warning but the authentication process still succeeds as expected. This is not the same scenario as @jawadatgithub described however it's worth making sure that this warning is not hiding some other problem.

2) For whoever is interested: my actual problem was the `CallbackPath` when using `UseWSFederationAuthentication` needs to be relative to the domain itself, and not relative to the IdentityServer module. So if your external provider is posting to `www.somedomain.com\SomeSubDir\core\MyAdfsPath` then the `CallbackPath` should be the full `\SomeSubDir\core\MyAdfsPath` rather than just `\core\MyAdfsPath`. This wasn't immediately obvious to me (I would just get a 404 and nothing interesting in the logs besides the CORS warning). Not sure if a more meaningful warning could be logged or at least note this in the documentation.

**Comment by leastprivilege** [comment] 2015-05-18 04:30
Yes this is indeed a gotcha. Feel free to make a comment in the docs.

**Comment by leastprivilege** [comment] 2015-05-20 06:44
Will you do that?

**Comment by PoyaManouchehri** [comment] 2015-05-20 12:01
I created a pull request in the doco.

Just wanted to repeat that this still does not fully answer the original issue. Just want to make sure I'm not hijacking this issue :)

**Comment by imperugo** [comment] 2015-05-20 13:02
Hi, 
sorry for the delay I think the problem still here, I've updated my production environment with the lasted version of idsrv and I still get this warning during login.
The code is exactly what I opened in this thread so, if it's right, the problem still here.
Maybe, privately, I can share mycode/environment so you can see when and why it happens.

**Comment by brockallen** [comment] 2015-05-27 14:47
@imperugo I emailed you in an attempt to obtain a sample that reproduced this issue.

**Comment by imperugo** [comment] 2015-05-27 14:53
Hi,
@brockallen email received. I'll create an user for you into our QA environment so you can see the html requests and the missing origin and send you our idsrv configuration soon (I'll back in office tomo).

Soon news
.u

**Comment by brockallen** [comment] 2015-05-31 18:06
Any update? If not, I'd like to close the issue. Thanks.

**Comment by brockallen** [comment] 2015-06-05 15:00
Ok, I was finally able to see this in the logs in my environment. This is due to Chrome adding the Origin header when POSTing to the login (logout, consent, etc) page -- that's all. So in a sense, it's a false warning message. I'm not sure why Chrome is doing this. Firefox does not.

**Comment by brockallen** [comment] 2015-06-05 15:06
So according to this suggestion, I'll add a guard to check against the current origin: https://stackoverflow.com/questions/15512331/chrome-adding-origin-header-to-same-origin-request

**Comment by brockallen** [comment] 2015-06-05 15:15
Ok, I added this fix. Please test and let me know how it works for you. https://github.com/IdentityServer/IdentityServer3/commit/e7e19f9ca29f20e624457549e91012bc82100b66

**Comment by brockallen** [comment] 2015-06-11 15:53
Just pushed this fix to 1.6.2 to NuGet

**Closed** 2015-06-11 15:52 UTC
Labels: 3 - Done, question

**Comment by pasomaal** [comment] 2015-07-17 14:50
Hi, I'm experiencing the same problem. The problem with CallBackPach seems not to be solved in IdentityServer3 version 1.6.2.

I configured WsFederationAuthentication to be able logon with a Belgian eID card.
I'm using a CallbackPath and when I logon in Chrome there is still the CORS warning below:

Thinktecture.IdentityServer.Core.Configuration.Hosting.CorsPolicyProvider | CORS request made for path: /eid from origin: https://www.e-contract.be but rejected because invalid CORS path

This warning doesn't show up when logging on from within Internet Explorer.

The code:
```
var eIdAuth = new WsFederationAuthenticationOptions
{
                AuthenticationType = "EID",
                Caption = "eId",
                SignInAsAuthenticationType = signInAsType,
                MetadataAddress = "https://www.e-contract.be/eid-idp/endpoints/ws-federation/metadata/auth-metadata.xml",
                Wtrealm = "https://localhost:44333/core/eid",
                CallbackPath = new PathString("/core/eid")
};
app.UseWsFederationAuthentication(eIdAuth);
```
The problem also occurs when configuring ADFS with a callbackpath e.g. new PathString("/core/adfs").

When I modify the internal IdentityProvider3 code below and add "adfs" and "eid" to the paths passed to the CorsPolicyProvider, the warning seems to be fixed.

```
namespace Owin
{
    internal static class UseCorsExtension
    {
        public static void UseCors(this IAppBuilder app)
        {
            app.UseCors(new Microsoft.Owin.Cors.CorsOptions
            {
                PolicyProvider = new CorsPolicyProvider(Constants.RoutePaths.CorsPaths)
            });
        }
    }
}
```

Kind Regards,

Patrick Vandewiele

**Comment by dcinzona** [comment] 2015-08-12 13:42
I am also experiencing this error - even testing on local.
I have implemented a InMemoryCorsPolicyProvider class that returns true, regardless of the Clients AllowedOrigins. I still get this error running on localhost
```
CORS request made for path: /logout from origin: https://localhost:44308 but rejected because invalid CORS path
```

**Comment by dcinzona** [comment] 2015-08-12 14:13
Just kidding, updated to 1.6.2 just now (didn't realize I was still on 1.6.1)
