### ISSUE TITLE
WSFederation Callback CORS Issue with Chrome using WindowsAuthentication Plugin

### ISSUE THREAD

**Issue by jacobhlawlor** [IdentityServer/IdentityServer3#2427] opened 2016-01-15 18:10 UTC
While implementing SSO, I ran into the Chrome specific CORS issue detailed by pasomaal on Jul 17, 2015 in issue 1293 which has been closed. https://github.com/IdentityServer/IdentityServer3/issues/1293

To resolve, I had to abandon NUGET and modify the source code Constants.RoutePaths.CorsPaths passed internally to CorsPolicyProvider with my "adfs" Callback path.

Unless I am missing something, which is quite possible, making CorsPaths externally extensible somehow would eliminate the need for unnecessary core source code manipulation.

Reproduction Scenario:
* Identity Server 3 v2.3.0 Web Host as a standalone IDP with local user store (no passwords) hosted at "/identity" sub path segment
* WindowsAuthentication plugin v1.0 standalone Web Host configured for Windows Authentication
* Localhost development environment using IIS Express and Chrome testing with SPA Implicit Flow client
* In the Identity Server core IDP Web Host configure external identity provider to UseWsFederationAuthentication with MetadataAddress pointing to separate Windows Auth Web Host base url and with CallbackPath = new PathString("/identity/adfs");
* In the Windows Authentication Web Host set the IdpReplyUrl = "https://localhost:####/identity/adfs" which is the url to the Identity Server WebHost root path plus the "adfs" Callback path segment.

**Comment by leastprivilege** [comment] 2016-01-16 15:36
I can't repro that.

The host sample works for me in Chrome and we have both ADFS and the Windows Auth Service.

**Comment by leastprivilege** [comment] 2016-01-25 07:11
is this resolved?

**Comment by jacobhlawlor** [comment] 2016-01-25 17:47
Not with the localhost environment described above running with IIS Express.

**Comment by brockallen** [comment] 2016-01-25 17:57
Would you mind testing on 2.4 from CI/myget feed?

**Comment by jacobhlawlor** [comment] 2016-01-25 18:50
Absolutely.  I'll try testing later this week with the following NuGet packages from https://www.myget.org/gallery/identity 

IdentityServer3 v2.4.0-build00403
IdentityServer3.WsFederation v2.0.5-build00031
IdentityServer.WindowsAuthentication v1.0.0-build00005

Thanks.

**Comment by brockallen** [comment] 2016-01-30 02:59
Any update?

**Comment by jacobhlawlor** [comment] 2016-01-31 01:27
Testing with the latest https://www.myget.org/gallery/identity packages in a localhost IIS Express development environment and a deployed production IIS environment with Chrome show the same warning message in the Identity Server service trace log:

CORS request made for path: "/adfs" from origin: "https://xyz.com" but rejected because invalid CORS path

**Comment by brockallen** [comment] 2016-01-31 01:51
I guess what should be asked is "what is the /adfs path"?

**Comment by jacobhlawlor** [comment] 2016-01-31 07:25
My IDSvr3 project is configured to "https://somedomain.com/identity"
  Startup ConfigureExternalIdentityProviders() WsFederationAuthenticationOptions sets the CallbackPath to "/identity/adfs"

My WindowsAuthentication project Startup WindowsAuthenticationOptions sets IdpReplyUrl to "https://somedomain.com/identity/adfs"

**Comment by brockallen** [comment] 2016-01-31 14:58
And so you're making these requests all in ajax calls? That seems like an abnormal approach.

But anyway, that path is your path not our path, so configure CORS however you want.

**Comment by jacobhlawlor** [comment] 2016-01-31 16:24
No. Configuration is being done in Owin Middleware following the Identity Server 3 documentation for the WindowsAuthentication plugin and guidance from https://github.com/IdentityServer/IdentityServer3/issues/1463 (leastprivilege commented on Jun 12, 2015)

Even with CORS configured to accept all origins, the warning still shows up in the logs.  The point is that the only way I or pasomaal (https://github.com/IdentityServer/IdentityServer3/issues/1293) could eliminate the issue was to modify the Constants file in the core Identity Server 3 source code.

**Comment by brockallen** [comment] 2016-01-31 16:40
So test with other browsers. It sounds like the Chrome specific behavior and the output you get int he logs is a chrome specific red herring. We tried to add logic to prevent this from occurring, but perhaps based on your configuration we missed something.

**Comment by leastprivilege** [comment] 2016-02-13 16:44
all set?

**Comment by jacobhlawlor** [comment] 2016-02-16 17:47
I still have the issue reported, but Brock indicated it is a red herring.  To eliminate the error in the logs I had to modify the IDS core source code Constants.RoutePaths.CorsPaths.  Our app is built on chrome, so other browsers do not matter in our case.  I'll revisit in a few months and see what I can do to get back on the standard IDS NUGET package releases.

**Comment by dzintaras** [comment] 2016-02-23 13:51
Hi, we have also hit this issue. It's kinda chrome specific issue (also checked Firefox and IE) but we can't blame it and leave it just like that in hope it will be "fixed" by chrome because according to RFC 6454 this behavior is allowed:"The user agent MAY include an Origin header field in any HTTP request." (http://tools.ietf.org/html/rfc6454#section-7.3)
So maybe a way to avoid these "fake" warnings in logs we could make ability to white-list some paths. As far as I understand the situation everyone using external provider and using callback would face this.

**Comment by leastprivilege** [comment] 2016-02-24 07:07
maybe change the log output? @brockallen

**Comment by dzintaras** [comment] 2016-02-24 16:09
Changing the log output will hide this issue from warnings and errors monitoring but it will not be correct for a "real CORS request violation"

**Comment by brockallen** [comment] 2016-03-29 16:52
What version are you on? This commit was made last year and I was under the impression that it solved the chrome/origin/cors issue: https://github.com/IdentityServer/IdentityServer3/commit/e7e19f9c#diff-3d425bd9f6dc4ef8b4f1ae3a1ed1f5a8R50

**Comment by brockallen** [comment] 2016-03-29 16:55
Ah, but perhaps you were having issues due to running behind a proxy server? This commit in January addressed that: https://github.com/IdentityServer/IdentityServer3/commit/b9839c5d06914cddff11890ba7dc134650b7c41c

**Comment by dzintaras** [comment] 2016-03-30 11:51
We use v2.4 and yes requests are running behind HaProxy proxy. But I don't see how this affects the situation: if you use external identity provider (MS Azure in our case) then after successful authentication there is always POST to some callback and bang we get that  CORS warning.
By using https://github.com/IdentityServer/IdentityServer3/blob/master/source/Host.Configuration/IdentityServerExtension.cs Azure AD sample you should be able to reproduce it

**Comment by brockallen** [comment] 2016-03-30 15:17
Ah ok -- I now see. I was never clear on the repro for your scenarios.

POST responses from the external IdP (when the origin header is included) look like a real cors request, so the only thing that we can do is lower the logging to info.

**Comment by dzintaras** [comment] 2016-03-31 10:28
Of course thats always the option. But in this way we kind of don't solve the problem but just hide it. Why not just enable white-listing that external IdP callback url?

**Comment by brockallen** [comment] 2016-03-31 14:07
So a white list of origins that seems to be making CORS requests to prevent us from treating it like a CORS request? Naming is hard enough -- not sure what name we'd give this int he config... :/

**Comment by dzintaras** [comment] 2016-04-01 08:24
I meant making it possible to enter custom Url for at least considering it allowed. Currently it's constant value https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Configuration/AppBuilderExtensions/UseCorsExtension.cs

**Comment by leastprivilege** [comment] 2016-04-01 09:03
Sorry for jumping in - I might be missing context.

The problem is not that something is not working because we block any CORS requests? The problem is that in the logs some of the request show up as warnings?

**Comment by brockallen** [comment] 2016-04-01 18:39
He's asking for a new global configuration property of origins that we should always ignore for CORS, and consequently not log a message when they ask for CORS and they're not allowed.

**Comment by dzintaras** [comment] 2016-04-04 07:52
Yes - scenario with external IdP works but we get flood of warnings.
Yes lowering log output would ~~solve~~ (hide) warnings in logs. But then why have them at all if we gone ignore them?

**Comment by leastprivilege** [comment] 2016-04-04 15:45
So my question is again - the only reason to add that feature would be to remove these false negatives from the logs??

You know that logging is not recommended for production?

**Comment by dzintaras** [comment] 2016-04-05 07:15
Yes - the only reason to not have lots of warnings in logs.
And its the first time I'm hearing recommendation to not have logging (especially concerning warnings and errors) in production could elaborate more on that

**Comment by leastprivilege** [comment] 2016-04-11 04:53
Have you read the docs?

https://identityserver.github.io/Documentation/docsv2/configuration/logging.html

**Comment by dzintaras** [comment] 2016-04-11 12:37
I though that would be the case. Yes I have read documentation and we do use events. But also WARN and upper level logging - in my defense not everything gets raised as events (for example AntiForgery validation failures in case someone tries hacking you IdP).
Anyway I can see v2.5 is out and all those CORS warnings became info's so we can close this now. Thanks for information

**Closed** 2016-04-11 12:38 UTC
Labels: question
