### ISSUE TITLE
Different authority for multi-tenant application

### ISSUE THREAD

**Issue by Fqadri** [IdentityServer/IdentityServer3#3622] opened 2017-04-05 22:34 UTC
- [x] I read and understood how to enable [logging](https://identityserver.github.io/Documentation/docsv2/configuration/logging.html)

### Question / Issue
Below is our current code. What we are planning on supporting is optionally providing tenant id explicitly in our website url and using that as authentication authority. 

e.g. 
www.somesite.com         // This will be default behavior where Authority is https://login.microsoftonline.com/common

www.somsite.com/?t=myazureadd.onmicrosoft.com    //here if we see a query parameter "t" present we want to change the Authority at runtime.

```

 app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
  {
         AuthenticationMode = AuthenticationMode.Active,
         ClientId = clientId,
         Authority = "https://login.microsoftonline.com/common",
         TokenValidationParameters = new TokenValidationParameters
          {
               ValidateIssuer = false,
               SaveSigninToken = true
          },
...
...

```

The issue is this pipeline is build during start up and the only way I can think of updating Authority is in `RedirectToIdentityProvider` notification. I tried setting to

```
if (context.ProtocolMessage.RequestType == OpenIdConnectRequestType.AuthenticationRequest)
                        {
                            context.Options.Authority = "https://login.microsoftonline.com/azureadd.onmicrosoft.com";

                        }
```
This still went to common auth endpoint. Is there a way to override this value ?

### Relevant parts of the log file

```
<log goes here>
```

**Comment by rdavisunr** [comment] 2017-04-06 22:43
Maybe you could create a custom ConfigurationManager implementation and assign it to ConfigurationManager property of OpenIdConnectAuthenticationOptions?

Something like this:

```
public class DynamicConfigurationManager : IConfigurationManager<OpenIdConnectConfiguration>
{
    private ConfigurationManager<OpenIdConnectConfiguration> _inner;

    public async Task<OpenIdConnectConfiguration> GetConfigurationAsync(CancellationToken cancel)
    {
        if (_inner == null)
        {
            // figure out which authority you need here...
            string metadataAddress = "";

            if (!metadataAddress.EndsWith("/", StringComparison.Ordinal))
            {
                metadataAddress += "/";
            }

            metadataAddress += ".well-known/openid-configuration";

            _inner = new ConfigurationManager<OpenIdConnectConfiguration>(metadataAddress);
        }

        return await _inner.GetConfigurationAsync(cancel);
    }

    public void RequestRefresh()
    {
        _inner.RequestRefresh();
    }
}
```

Here's [another example](https://github.com/dzimchuk/azure-ad-b2c-asp-net-core/blob/master/TestApp/Infrastructure/PolicyConfigurationManager.cs) of modifying the authority using this approach...

**Comment by brockallen** [comment] 2017-04-09 15:30
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/

**Closed by brockallen** 2017-04-09 15:30 UTC
