### ISSUE TITLE
Issue with LocalAuthenticationContext

### ISSUE THREAD

**Issue by Marfusios** [IdentityServer/IdentityServer3#3057] opened 2016-07-12 15:22 UTC
Hello,

I got my custom user service:

```csharp
public class CustomService : UserServiceBase
{
    public override Task AuthenticateLocalAsync(LocalAuthenticationContext context)
    {
         var email = context.UserName;
         var password = context.Password;
         
         ... 
    }
}

// And registered via IdentityServerServiceFactory
var factory = new IdentityServerServiceFactory();
var userService = new CustomService();
factory.UserService = new Registration<IUserService>(userService);
```

Everything worked great, but right now I updated all libraries to the new versions and there is issue with LocalAuthenticationContext. 
"context.UserName" contains always values from previous request (only first one). So everything works just for first request, but all others are lost...

Do you know what could be the cause of it?

Versions:
        "Microsoft.AspNetCore.Mvc": "1.0.0",
        "Microsoft.AspNetCore.Cors": "1.0.0",
        "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
        "Microsoft.AspNetCore.Owin": "1.0.0",
        "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
        "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
        "Microsoft.Extensions.Configuration.Json": "1.0.0",
        "Microsoft.Extensions.Logging": "1.0.0",
        "Microsoft.Extensions.Logging.Console": "1.0.0",
        "Microsoft.Extensions.Logging.Debug": "1.0.0",
        "Microsoft.Owin": "3.0.1",
        "Microsoft.Owin.Cors": "3.0.1",
        "Microsoft.Owin.Host.SystemWeb": "3.0.1",
        "Microsoft.AspNetCore.DataProtection": "1.0.0",
        "IdentityServer3": "2.5.1",
        "Serilog": "1.5.14",
        "Owin": "1.0.0",
        "RestSharp": "105.2.3",

I use new project system from .NET Core (xproj, project.json). 
I've tried IdentityServer3 version 2.5.0, same issue.

**Comment by brockallen** [comment] 2016-07-12 21:03
> factory.UserService = new Registration<IUserService>(userService);

This way of using the registration configures a singleton. I suspect that's not what you want and the cause of your issue.

**Comment by Marfusios** [comment] 2016-07-13 10:08
Ok, but it has worked correctly (even if singleton).

I did investigation today and the issue started to occur when I had converted an application from .NET Core rc2 to RTM. I've removed all my libraries from project.json and definitely at least one of these libraries break IdentityServer3 functionality:

        "Microsoft.AspNetCore.Mvc": "1.0.0",
        "Microsoft.AspNetCore.Cors": "1.0.0",
        "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
        "Microsoft.AspNetCore.Owin": "1.0.0",
        "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
        "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
        "Microsoft.Extensions.Configuration.Json": "1.0.0",
        "Microsoft.Extensions.Logging": "1.0.0",
        "Microsoft.Extensions.Logging.Console": "1.0.0",
        "Microsoft.Extensions.Logging.Debug": "1.0.0",
        "Microsoft.AspNetCore.DataProtection": "1.0.0"
Just changed '1.0.0-rc2-final' to '1.0.0'.

I've tried to remove singleton:
```csharp
var factory = new IdentityServerServiceFactory();
factory.UserService = new Registration<IUserService>(resolver => new CustomService());
```

But it still returns values from first request (LocalAuthenticationContext)

**Comment by brockallen** [comment] 2016-08-10 19:01
I'll close this since #3059 seems to be the same.

**Comment by brockallen** [comment] 2016-08-10 19:02
Hmmm, maybe they're not the exact same...

**Comment by brockallen** [comment] 2016-08-11 18:00
Here's my proposal for fixes based upon this and other PRs: https://github.com/IdentityServer/IdentityServer3/pull/3132

**Comment by brockallen** [comment] 2016-08-12 16:57
Ok, I merged it. Thanks for everyone researching this and essentially solving the problem with your efforts and PRs. Thanks!

**Closed by brockallen** 2016-08-12 16:57 UTC
Labels: bug
